name: Deploy
on:
  push:
    branches:
      - main
jobs:
  version-mono:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - env:
          BRANCHNAME: ${{github.ref_name}}
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@github.com"
          echo "branch name is $BRANCHNAME"
          echo "running env"
          env
          echo "getting commit"
          git log -1 --format="%H"
          DATESTR=`date +"%Y-%m-%d"`
          TAG="$DATESTR/$BRANCHNAME"
          echo "TAG WOULD BE $TAG"
          echo git tag -a "$TAG" -m "$TAG"
          echo git push origin "$TAG"