name: Deploy
on:
  push:
    branches:
      - main
jobs:
  version-mono:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@github.com"
          echo "running env"
          env
          echo "getting commit"
          COMMIT=`git log -1 --format="%H"` echo $COMMIT