name: Deploy
on:
  release:
    types: [published]
jobs:
  version-mono:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@github.com"
          env
          echo stuff
          git rev-list --tags --skip=1 --max-count=1
          echo more stuff
          git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`
          echo on we go
          PREV_TAG_HASH=$(git rev-list --tags --skip=1 --max-count=1)
          PREV_TAG=$(git describe --abbrev=0 --tags $PREV_TAG_HASH)
          echo "prev tag hash is $PREV_TAG_HASH"
          echo "prev tag is $PREV_TAG"
          echo "curr hash is $GITHUB_SHA"
          echo "curr ref is $GITHUB_REF_NAME"
          echo git diff "origin/$GITHUB_REF_NAME" "origin/$PREV_TAG_HASH"
          git diff "origin/$GITHUB_REF_NAME" "origin/$PREV_TAG"
          