name: Test Stuff
on:
  push:
    branches-ignore:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - env:
          BRANCHNAME: ${{github.ref_name}}
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@github.com"
          DATESTR=`date +"%Y-%m-%d"`
          TAG="$DATESTR/$BRANCHNAME"
          echo "tag is $TAG"
          