name: Test Stuff
on:
  push:
    branches-ignore:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@github.com"
          echo "running env"
          env
          echo "getting commit"
          git log
          git log -1 --format="%H"
          X=`git log -1 --format="%H"` && echo "COMMIT IS $X"
          